### ISSUE TITLE
It is not compatible with mongo_dart 

### ISSUE THREAD

**Issue by lotictech** [princeflutterdev/flutter_upi_pay#7]
While working on project Ihave trying to use MongoDB and added dependency mongo_dart, it was not adding due to flutter_upi_india showing the error:
Resolving dependencies...
Because mongo_dart >=0.8.0-1.0.beta depends on decimal ^2.2.0 and flutter_upi_india 0.0.6 depends on decimal ^3.0.2, mongo_dart >=0.8.0-1.0.beta is incompatible with flutter_upi_india 0.0.6.
And because no versions of flutter_upi_india match >0.0.6 <0.1.0, mongo_dart >=0.8.0-1.0.beta is incompatible with flutter_upi_india ^0.0.6.
So, because schooltrack depends on both flutter_upi_india ^0.0.6 and mongo_dart ^0.9.4, version solving failed.
exit code 1

**Comment by princeflutterdev** [comment]
for this you can override the mongo_dart package in your project. and issue will be resolved.

**Comment by lotictech** [comment]
I have override in yaml file but that doest work
dependency_overrides:
  mongo_dart: ^0.10.3
  
  same error

**Comment by princeflutterdev** [comment]
> I have override in yaml file but that doest work dependency_overrides: mongo_dart: ^0.10.3
> 
> same error

sorry my bad you have override the decimal package not mongo_dart

**Comment by lotictech** [comment]
As I m new to this language so don't have that much idea about your suggestion but now got the details and app is running without error .
